### ISSUE TITLE
Mine Btc withdraw pending

### ISSUE THREAD

**Issue by mahran786** [blockchain/blockchain-wallet-v4-frontend#1203]
# 🐛 Bug Report 🐛

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by mahran786** [comment]
Miner btc withdraw pending

**Comment by mahran786** [comment]
How ?

**Comment by mahran786** [comment]
How ? Closed thus issue. Solve my issue please.

**Comment by plondon** [comment]
There is no information provided

**Comment by mahran786** [comment]
Which type of information ?

**Comment by plondon** [comment]
Description, screen shots, expected behavior, repro steps, additional email. The only info provided is “transaction from miner pending”. The wallet does not know who this miner is, i do not know what the transaction is, i do not know how it was constructed. Therefore, due to the lack of information I have closed this. If you would like to open another issue with the required info I would be happy to help.
