### ISSUE TITLE
clear way to export my wallet

### ISSUE THREAD

**Issue by helloitsme123zz** [blockchain/blockchain-wallet-v4-frontend#1650]
how to clearly know my bitcoin cash abc wallet 12 words ?
and specifically for a specific address
how to also specifically know the private key clearly for my bitcoin cash abc wallet with blockchain.com or even the btc wallet?
its been 3 years for me trying to with no success and am afraid to keep huge amount in the wallet as if i lost the access the 12 words i have wont solve my problem as long as idk how to turn them into private key clearly in a safe way or even if this 12 words for the whole account or specific wallet or currency, please help thanks !

**Comment by plondon** [comment]
> how to clearly know my bitcoin cash abc wallet 12 words ?
Security Center => Backup Phrase (on the bottom) => Backup Funds. This will show you your 12 word recovery phrase. If you've already done this then you can review the words again.
> and specifically for a specific address
The phrase is used as the seed. You derive addresses via pathways from that seed.
> how to also specifically know the private key clearly for my bitcoin cash abc wallet with blockchain.com or even the btc wallet?
We don't expose private keys because it's another attack surface. If you have your mnemonic you have your private keys. https://iancoleman.io/bip39/ _if you really want to get your private keys_ this tool can generate them for you. Or if you're technical you can use the [bitcoinjs library](https://github.com/bitcoinjs/bitcoinjs-lib) we use. I dont really recommend iancoleman as I can't verify the source code, but I use it all the time for testing.
> its been 3 years for me trying to with no success and am afraid to keep huge amount in the wallet as if i lost the access the 12 words i have wont solve my problem as long as idk how to turn them into private key clearly in a safe way or even if this 12 words for the whole account or specific wallet or currency
Just don't lose your mnemonic :)

**Comment by helloitsme123zz** [comment]
so you say the 12 words covers all my wallet with all its currencies that's a good point.
but the issue remains in the point of getting the private key, till now in the whole world there's still no trusted method for the not programmers to get their PK in a safe way? must always remain in danger?

"" I dont really recommend iancoleman as I can't verify the source code ""

thank you for replying

**Comment by plondon** [comment]
> but does this works only will export all if in blockchain wallet or any other wallet to put in it the private key of my 12 words will get back all the wallets in different cryptos with the balance?

Any other wallet, electrum, or exodus for example. Our BCH chain is not totally compliant with bip44 though because we are still on the 0' purpose path `m/44'/0'/0/0`. So if you recover into a wallet that uses `m/44'/145'/0/0` your balance will not show up because the funds are on a different path. In that case I recommend sending from BC to your new wallet.

> but the issue remains in the point of getting the private key

What do you mean by 'the private key', which private key? Your account generates infinite number of pub/prv key pairs. The private key for the first receive address, the private key for the 20th change address? Your mnemonic generates all of these.

For example go to https://iancoleman.io/bip39/. 

Click generate

<img width="597" alt="Screen Shot 2019-06-03 at 7 47 13 AM" src="https://user-images.githubusercontent.com/5640772/58799624-d33b8e00-85d3-11e9-9528-ebec535d5856.png">

This will create a seed which can be encoded into your mnemonic.
Scroll down to see derived addresses from that seed. Are these the private keys you want?

**Instead of asking how to get all your private keys from your mnemonic maybe ask why that is necessary?**

**Comment by helloitsme123zz** [comment]
my understand of the private key for my wallet. is once blockchain.com for example is down forever and suddenly i still have my funds and they're not lost just by using this thing called private key so i can make my funds appear in some other wallet services for example.

this is all what i am worried about, once blockchain.com ain't available forever what i will have to do by the 12 words i have in steps to be able to catch my funds somewhere else ? that's all. or if i completely lost the access to my blockchain.com wallet and just have the 12 words, what i'll do in steps to get my funds in a new blockchain.com account with only having the 12 words.

its all what am worried about,

because in blockchain.com when i try to merge a wallet for example it says enter the wallet private key, it dont say anything about enter the 12 words of the account you want to merge

what i understand is that 12 words ain't the recovering thing, but its something i have to do another thing by it to figure out the recovering password " private key " if i am right, what i should do using my 12 words to move my wallet into another blockchain account and if i am wrong what's the right thing for this 12 words usage to move my funds from .. to .. if i lost the wallet access?

thank you

**Comment by plondon** [comment]
> because in blockchain.com when i try to merge a wallet for example it says enter the wallet private key, it dont say anything about enter the 12 words of the account you want to merge

Where do we say this? Are you talking about _importing an address_

>  is once blockchain.com for example is down forever

**All you need is your 12 words**

**Comment by helloitsme123zz** [comment]
yes, here in this picture.

or how do i import my blockchain wallet to another blockchain wallet? i dont see any other options to do this except providing the called private key, check this picture >

![ay](https://user-images.githubusercontent.com/51269150/58804310-dc4b5000-8611-11e9-8ddb-c01abc3449d5.png)


how to import a whole blockchain.com wallet to another blockchain.com wallet?

**Comment by plondon** [comment]
> how to import a whole blockchain.com wallet to another blockchain.com wallet?

https://login.blockchain.com/#/recover

Although why you would do this I have no idea

**Comment by helloitsme123zz** [comment]
Although why you would do this I have no idea

not gonna do it, just getting to know how to so once i lose access to my wallet i dont lose my mind, preparing myself for the future darkness :D

thank you for the help gonna review the link now

**Comment by shaubrel** [comment]
@helloitsme123zz 
did you resolve to your blockchain wallet issue, If you couldn't, I can restore your wallet for you, contact me: anywalletrecovery@gmail.com
