### ISSUE TITLE
valcharo92

### ISSUE THREAD

**Issue by chicharelli92** [blockchain/blockchain-wallet-v4-frontend#1885]
# 🐛Bug Report 🐛
***Do***
1. Follow [this guide](https://www.draw.io/#G1QFFRM0KBAJBCMLpm3Rb9OcyxFO-enz_A)
2. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
3. Provide as much information as possible

***Don't***
1. Leave this form blank
2. Provide personal information
3. Provide your GUID, password, or email

*Failure to follow the do's and don'ts will result in us closing the issue without further dialogue*

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by chicharelli92** [comment]
> # 🐛Bug Report 🐛
> 
> _**Do**_
> 
>     1. Follow [this guide](https://www.draw.io/#G1QFFRM0KBAJBCMLpm3Rb9OcyxFO-enz_A)
> 
>     2. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
> 
>     3. Provide as much information as possible
> 
> 
> _**Don't**_
> 
>     1. Leave this form blank
> 
>     2. Provide personal information
> 
>     3. Provide your GUID, password, or email
> 
> 
> _Failure to follow the do's and don'ts will result in us closing the issue without further dialogue_
> ## Description
> 
> Provide a clear and concise description of the issue.
> ## Expected Behavior
> 
> Explain what you would expect to happen.
> ## Reproduction Steps
> 
> Enter detailed steps to reproduce the issue.
> ## Screenshots/Logs
> 
> If available, please provide any relevant screenshots or logs.
> ## Additional Information
> 
> Add any addition information that might be useful to our team.

Oo

**Comment by chicharelli92** [comment]
Duplicate of #

**Comment by Milan-Popich** [comment]
Fuck that guide
version 2.18 on a iPhone 10x when in reality it should be 4.2.2
The FUC-King e-mail verification is not even going through.
Also my money that was in my wallet before AI recovered it is not showing up in my wallet.
EXPECTED BEHAVIOR
FOR MY MONEY TO BE IN MY WALLET.
IS THIS WHERE I REQUEST MY MINING REWARD OF 50 BTC FOR MINING BLOCK #1 at?
I TRIED REQUESTING IT MANY TIMES TO THE BLOCKCHAIN SUPPORT WITHOUT Any luck.

In Health,
Milan Popich

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Op donderdag, oktober 10, 2019 4:03 PM, chicharelli92 <notifications@github.com> schreef:
