### ISSUE TITLE
https://login.blockchain.com/wallet/import-wallet is broken (Wrong captcha)

### ISSUE THREAD

**Issue by dev1ns** [blockchain/blockchain-wallet-v4-frontend#4157]
# 🐛Bug Report 🐛

## Description
When trying to recover an old "wallet.aes.json" file on https://login.blockchain.com/wallet/import-wallet , the last step fails with "Wrong captcha" error.

## Expected Behavior
Wallet is successfuly recovered.

## Reproduction Steps
Drag and drop wallet.aes.json file on https://login.blockchain.com/wallet/import-wallet, enter decryption password, complete "Enter new password" modal screen, click Continue.

## Screenshots/Logs

<img width="924" alt="Screen Shot 2022-02-04 at 9 43 09 AM" src="https://user-images.githubusercontent.com/95230650/152484888-10c3e065-546f-4f51-987f-399db1fe99c6.png">

## Additional Information

The error was probably introduced by this PR: https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/4104 @schnogz

**Comment by doge2021** [comment]
@dev1ns when you check the console you may see an error of "invalid padding length of xx bytes..."
if so, it is caused by a bug of the wallet. as the private key is not in the normal format. can only decrypt it manually and modify the privatekey to normal one. if you dont know how to do it, you may reach [BTC recover](https://twitter.com/Btc2doge) on twitter. he recovered mine with same error.

**Comment by doge2021** [comment]
@dev1ns https://github.com/blockchain/blockchain-wallet-v4-frontend/issues/4238 #

**Comment by DanielsBerlin** [comment]
shame on blockchain support and team
they have lead many users to loss of their assets with their piece of shit programming skill
shit has better programming skill than scam blockchain.com scammers
they don't even declarer that they are bad programmers
and don't answer emails I send them 15 emails and they prefer to keep silent because of this big goof they made
![Screenshot (2444)](https://user-images.githubusercontent.com/100190477/155728590-7f7b607e-71d9-4c9b-9c0c-a534d61e0613.png)

**Comment by isieditors** [comment]
@DanielsBerlin 
@dev1ns 
I have solved the same issue for my customer before. blockchain wont help you they don't respond.
If you still have the problem get in touch with me and I will help you.
you can fine my contact details on my profile

**Comment by DanielsBerlin** [comment]
@isieditors 
thanks for your message 
i got really disappointed
what is your email or telegram id??

**Comment by schnogz** [comment]
This is fixed for now.  It may break again in the future when we re-enable captcha but a long term fix will be pushed in the coming weeks.

**Comment by JustJackkie** [comment]
> This is fixed for now in production. It may break again in the future when we re-enable captcha but a long term fix will be pushed in the coming weeks.

Hey, facing the same issue here and I see a lot of other people having the same error. You mentioned in the comment it was fixed, could you specify how I can solve the issue? https://github.com/blockchain/service-my-wallet-v3/issues/570

**Comment by RishabSwift** [comment]
Why is this closed? This issue is still not resolved.
