### ISSUE TITLE
Assets in USD how do I get them 

### ISSUE THREAD

**Issue by Kelzbaby88** [blockchain/blockchain-wallet-v4-frontend#6415]
# 🐛Bug Report 🐛
***Do***
1. Fill out the **Description**, **Expected Behavior**, **Reproduction Steps**, **Screenshots/Logs**, and **Additional Information** below.
2. Provide as much information as possible

***Don't***
1. Leave this form blank
2. Provide personal information
3. Provide your GUID, password, or email

*Failure to follow the do's and don'ts will result in us closing the issue without further dialogue*

## Description
Provide a clear and concise description of the issue.

## Expected Behavior
Explain what you would expect to happen.

## Reproduction Steps
Enter detailed steps to reproduce the issue.

## Screenshots/Logs
If available, please provide any relevant screenshots or logs.

## Additional Information
Add any addition information that might be useful to our team.

**Comment by Singkanongna98** [comment]
Good.เมื่อ 20 ก.ค. 2024 07:22 Kelzbaby88 ***@***.***> เขียนว่า
Celsius Network LLC, et al.-court-dockets.xlsx
🐛Bug Report 🐛
Do
Fill out the Description, Expected Behavior, Reproduction Steps, Screenshots/Logs, and Additional Information below.Provide as much information as possible
Don't
Leave this form blankProvide personal informationProvide your GUID, password, or email
Failure to follow the do's and don'ts will result in us closing the issue without further dialogue
Description
Provide a clear and concise description of the issue.
Expected Behavior
Explain what you would expect to happen.
Reproduction Steps
Enter detailed steps to reproduce the issue.
Screenshots/Logs
If available, please provide any relevant screenshots or logs.
Additional Information
Add any addition information that might be useful to our team.

**Comment by Hammered72** [comment]
Looks good withdrawal

**Comment by RonGee72** [comment]
4031630974375023 pls add to this card

**Comment by Jjajsja** [comment]
> [Celsius Network LLC, et al.-expedientes judiciales.xlsx](https://github.com/user-attachments/files/16317794/Celsius.Network.LLC.et.al.-court-dockets.xlsx)
> 
> # 🐛Informe de error 🐛
> _**Hacer**_
> 
> 1. Complete la **descripción** , **el comportamiento esperado** , **los pasos de reproducción** , **las capturas de pantalla/registros** y **la información adicional** a continuación.
> 2. Proporcionar la mayor cantidad de información posible
> 
> _**No**_
> 
> 1. Deje este formulario en blanco
> 2. Proporcionar información personal
> 3. Proporcione su GUID, contraseña o correo electrónico
> 
> _Si no se siguen las reglas de qué hacer y qué no hacer, cerraremos el asunto sin más diálogo._
> 
> ## Descripción
> Proporcione una descripción clara y concisa del problema.
> 
> ## Comportamiento esperado
> Explica lo que esperarías que sucediera.
> 
> ## Pasos de reproducción
> Ingrese los pasos detallados para reproducir el problema.
> 
> ## Capturas de pantalla/Registros
> Si está disponible, proporcione capturas de pantalla o registros relevantes.
> 
> ## información adicional
> Agregue cualquier información adicional que pueda ser útil para nuestro equipo.

https://github.com/blockchain/blockchain-wallet-v4-frontend/issues/6415#issue-2420404249

**Comment by Kelzbaby88** [comment]
[BITO Holdings (2).csv](https://github.com/user-attachments/files/17017066/BITO.Holdings.2.csv)
