### ISSUE TITLE
Add Support for Testnet

### ISSUE THREAD

**Issue by lzhuor** [blockchain/blockchain-wallet-v4-frontend#771]
# 🐛 Bug Report 🐛

## Description
Hi team, I'm trying to connect to testnet from localhost:8080. However, I am getting below error during login:
```
hdnode.js:78 Uncaught Error: Invalid network version
    at Function.HDNode.fromBase58 (hdnode.js:78)
    at accountCons (HDAccount.js:124)
    at fromJS (HDAccount.js:130)
    at args.(anonymous function) (webpack:////Users/zhuoranli/IdeaProjects/public/blockchain-wallet-v4-frontend/node_modules/ramda/es/addIndex.js?:40:27)
    at _map (_map.js:8)
    at map (map.js:64)
    at eval (_dispatchable.js:42)
    at f2 (_curry2.js:30)
    at eval (addIndex.js:44)
    at eval (_curryN.js:38)
```

The `development.js` config is :
```javascript
module.exports = {
  ROOT_URL: 'https://testnet.blockchain.info',
  API_DOMAIN: 'https://api-testnet.blockchain.info',
  WEB_SOCKET_URL: 'wss://ws.blockchain.info/testnet3/inv',
  WALLET_HELPER_DOMAIN: 'https://wallet-helper.blockchain.info'
}
```
Could you please advise what can I do to connect to testnet via local environment? Do you mind providing a guide on how could developers start using testnet for development in local?

Thank you and greatly appreciate it!

## Expected Behavior
I should be able to login

## Reproduction Steps
`yarn start:dev` with above `development.js`

## Screenshots/Logs
![image](https://user-images.githubusercontent.com/40888558/42642270-12771f0e-8629-11e8-8aa1-1bc40f2089a2.png)

## Additional Information
NIL

**Comment by plondon** [comment]
Hi at @lzhuor thank you so much for using the wallet and contributing an issue!

The wallet does not yet support testnet, we've looked into it a little bit but have not had sufficient time to fully implement it. I believe the crux of the issue is here: https://github.com/blockchain/blockchain-wallet-v4-frontend/blame/development/packages/blockchain-wallet-v4/src/types/Wrapper.js#L157. Where the wallet is created but the network is not passed in.

We have some more work to do around network configurations, but this is definitely on the todo list! In the meantime, if its a testnet wallet you need you can use https://testnet.blockchain.info/wallet/#/login.

Actually, you may be able to create a testnet wallet there and then use it with the v4 config you have, since it may just be the creation of the wallet that is incorrect.

Best
Phil

**Comment by lzhuor** [comment]
Hi folks, I tried to fix the above problem in #803.

After the fix, in debug mode, I can see `network` is passed all the way down. However, I am getting below error after wallet creation:
![image](https://user-images.githubusercontent.com/14172220/43096281-2c1e671c-8eeb-11e8-851e-07c6c9114526.png)

The error was thrown from `kvStore/index.js` during calling `GET https://api-testnet.blockchain.info/metadata/1CH6gsibWwGqTTZYZ6cEuMKMTwJL1Wvfsq`

```
const fetchKVStore = kv => {
    let setKvFromResponse = curry((currentKv, res) => {
      if (res === null) return set(KV.value, null, currentKv)
      let setFromResponse = compose(
        set(KV.magicHash, prop('compute_new_magic_hash', res)),
        set(KV.value, KV.extractResponse(kv.encKeyBuffer, res))
      )
      return setFromResponse(currentKv)
    })

    return request('GET', kv.address)
      .map(KV.verifyResponse(kv.address))
      .chain(eitherToTask)
      .map(setKvFromResponse(kv))
      .rejectedMap(e => {
        console.error(
          `Failed to fetch metadata entry ${kv.typeId} at ${kv.address}:`,
          e
        )
        return new Error('METADATA_FETCH_FAILED')
      })
  }
```
Do you have an idea about the cause? Thank you for your time! ❤️

**Comment by lzhuor** [comment]
Thank you @plondon ! I will continue from here.

**Comment by plondon** [comment]
Bitcoin testnet wallet available here: https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/874
